# Generated by Django 6.0.6 on 2026-06-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuarios', '0004_remove_perfilestudiante_rango'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilestudiante',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='siguiendo', to='modulo_usuarios.perfilestudiante', verbose_name='Seguidores'),
        ),
    ]
